echo off
cd ..
SET root=%cd%
SET sourcePath=%root%\StreamCompressTest\TestData\Source
SET resultPath=%root%\StreamCompress\results
IF NOT EXIST %resultPath% MKDIR %resultPath%
SET resultFile=%resultPath%\output.csv
del %resultFile%

cd StreamCompress
dotnet build --configuration release
cd bin\release\netcoreapp2.1
copy %sourcePath%\00000-original.bmp %resultPath%\00000-original.bmp

dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScale.bmp --method AsGrayScale --crop-left-px 0 --crop-right-px 0 --crop-top-px 0 --crop-bottom-px 0 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop0.enc --method AsGZipEncoded --crop-left-px 0 --crop-right-px 0 --crop-top-px 0 --crop-bottom-px 0 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop2.enc --method AsGZipEncoded --crop-left-px 32 --crop-right-px 32 --crop-top-px 32 --crop-bottom-px 32 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop4.enc --method AsGZipEncoded --crop-left-px 64 --crop-right-px 64 --crop-top-px 64 --crop-bottom-px 64 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop6.enc --method AsGZipEncoded --crop-left-px 96 --crop-right-px 96 --crop-top-px 96 --crop-bottom-px 96 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop8.enc --method AsGZipEncoded --crop-left-px 128 --crop-right-px 128 --crop-top-px 128 --crop-bottom-px 128 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop10.enc --method AsGZipEncoded --crop-left-px 160 --crop-right-px 160 --crop-top-px 160 --crop-bottom-px 160 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop12.enc --method AsGZipEncoded --crop-left-px 192 --crop-right-px 192 --crop-top-px 192 --crop-bottom-px 192 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop14.enc --method AsGZipEncoded --crop-left-px 224 --crop-right-px 224 --crop-top-px 224 --crop-bottom-px 224 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop16.enc --method AsGZipEncoded --crop-left-px 256 --crop-right-px 256 --crop-top-px 256 --crop-bottom-px 256 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop18.enc --method AsGZipEncoded --crop-left-px 288 --crop-right-px 288 --crop-top-px 288 --crop-bottom-px 288 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop20.enc --method AsGZipEncoded --crop-left-px 320 --crop-right-px 320 --crop-top-px 320 --crop-bottom-px 320 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGZipEncoded-crop22.enc --method AsGZipEncoded --crop-left-px 352 --crop-right-px 352 --crop-top-px 352 --crop-bottom-px 352 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop0.enc --method AsLZ78Encoded --crop-left-px 0 --crop-right-px 0 --crop-top-px 0 --crop-bottom-px 0 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop2.enc --method AsLZ78Encoded --crop-left-px 32 --crop-right-px 32 --crop-top-px 32 --crop-bottom-px 32 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop4.enc --method AsLZ78Encoded --crop-left-px 64 --crop-right-px 64 --crop-top-px 64 --crop-bottom-px 64 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop6.enc --method AsLZ78Encoded --crop-left-px 96 --crop-right-px 96 --crop-top-px 96 --crop-bottom-px 96 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop8.enc --method AsLZ78Encoded --crop-left-px 128 --crop-right-px 128 --crop-top-px 128 --crop-bottom-px 128 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop10.enc --method AsLZ78Encoded --crop-left-px 160 --crop-right-px 160 --crop-top-px 160 --crop-bottom-px 160 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop12.enc --method AsLZ78Encoded --crop-left-px 192 --crop-right-px 192 --crop-top-px 192 --crop-bottom-px 192 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop14.enc --method AsLZ78Encoded --crop-left-px 224 --crop-right-px 224 --crop-top-px 224 --crop-bottom-px 224 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop16.enc --method AsLZ78Encoded --crop-left-px 256 --crop-right-px 256 --crop-top-px 256 --crop-bottom-px 256 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop18.enc --method AsLZ78Encoded --crop-left-px 288 --crop-right-px 288 --crop-top-px 288 --crop-bottom-px 288 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop20.enc --method AsLZ78Encoded --crop-left-px 320 --crop-right-px 320 --crop-top-px 320 --crop-bottom-px 320 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsLZ78Encoded-crop22.enc --method AsLZ78Encoded --crop-left-px 352 --crop-right-px 352 --crop-top-px 352 --crop-bottom-px 352 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop0.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 0 --crop-right-px 0 --crop-top-px 0 --crop-bottom-px 0 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop2.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 32 --crop-right-px 32 --crop-top-px 32 --crop-bottom-px 32 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop4.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 64 --crop-right-px 64 --crop-top-px 64 --crop-bottom-px 64 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop6.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 96 --crop-right-px 96 --crop-top-px 96 --crop-bottom-px 96 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop8.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 128 --crop-right-px 128 --crop-top-px 128 --crop-bottom-px 128 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop10.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 160 --crop-right-px 160 --crop-top-px 160 --crop-bottom-px 160 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop12.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 192 --crop-right-px 192 --crop-top-px 192 --crop-bottom-px 192 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop14.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 224 --crop-right-px 224 --crop-top-px 224 --crop-bottom-px 224 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop16.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 256 --crop-right-px 256 --crop-top-px 256 --crop-bottom-px 256 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop18.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 288 --crop-right-px 288 --crop-top-px 288 --crop-bottom-px 288 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop20.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 320 --crop-right-px 320 --crop-top-px 320 --crop-bottom-px 320 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsGZipEncoded-crop22.enc --method AsGrayScaleAsGZipEncoded --crop-left-px 352 --crop-right-px 352 --crop-top-px 352 --crop-bottom-px 352 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop0.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 0 --crop-right-px 0 --crop-top-px 0 --crop-bottom-px 0 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop2.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 32 --crop-right-px 32 --crop-top-px 32 --crop-bottom-px 32 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop4.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 64 --crop-right-px 64 --crop-top-px 64 --crop-bottom-px 64 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop6.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 96 --crop-right-px 96 --crop-top-px 96 --crop-bottom-px 96 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop8.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 128 --crop-right-px 128 --crop-top-px 128 --crop-bottom-px 128 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop10.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 160 --crop-right-px 160 --crop-top-px 160 --crop-bottom-px 160 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop12.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 192 --crop-right-px 192 --crop-top-px 192 --crop-bottom-px 192 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop14.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 224 --crop-right-px 224 --crop-top-px 224 --crop-bottom-px 224 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop16.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 256 --crop-right-px 256 --crop-top-px 256 --crop-bottom-px 256 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop18.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 288 --crop-right-px 288 --crop-top-px 288 --crop-bottom-px 288 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop20.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 320 --crop-right-px 320 --crop-top-px 320 --crop-bottom-px 320 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsLZ78Encoded-crop22.enc --method AsGrayScaleAsLZ78Encoded --crop-left-px 352 --crop-right-px 352 --crop-top-px 352 --crop-bottom-px 352 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop0.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 0 --crop-right-px 0 --crop-top-px 0 --crop-bottom-px 0 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop2.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 32 --crop-right-px 32 --crop-top-px 32 --crop-bottom-px 32 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop4.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 64 --crop-right-px 64 --crop-top-px 64 --crop-bottom-px 64 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop6.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 96 --crop-right-px 96 --crop-top-px 96 --crop-bottom-px 96 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop8.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 128 --crop-right-px 128 --crop-top-px 128 --crop-bottom-px 128 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop10.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 160 --crop-right-px 160 --crop-top-px 160 --crop-bottom-px 160 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop12.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 192 --crop-right-px 192 --crop-top-px 192 --crop-bottom-px 192 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop14.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 224 --crop-right-px 224 --crop-top-px 224 --crop-bottom-px 224 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop16.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 256 --crop-right-px 256 --crop-top-px 256 --crop-bottom-px 256 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop18.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 288 --crop-right-px 288 --crop-top-px 288 --crop-bottom-px 288 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop20.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 320 --crop-right-px 320 --crop-top-px 320 --crop-bottom-px 320 >>%resultFile%
dotnet StreamCompress.dll --source-path %resultPath% --source-file-suffix original.bmp --destination-path %resultPath% --destination-file-suffix AsGrayScaleAsHuffmanEncoded-crop22.enc --method AsGrayScaleAsHuffmanEncoded --crop-left-px 352 --crop-right-px 352 --crop-top-px 352 --crop-bottom-px 352 >>%resultFile%

cd ..\..\..

